api:
    build: .
    ports:
        - "8080:8080"
    volumes:
        - .:/app
    links:
        - db
    tty: true
    stdin_open: true
db:
    image: postgres:9.5
    environment:
        - POSTGRES_PASSWORD=ctx
        - POSTGRES_USER=ctx
