api:
    build: .
    ports:
        - "8080:8080"
    volumes:
        - .:/app
    links:
        - db
    tty: true
    stdin_open: true
db:
    image: kevinjqiu/couchdb
    environment:
        - COUCHDB_PASS=passw0rd
    ports:
        - "5984:5984"
